In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.preprocessing.image import load_img, img_to_array

# Data Preparation
image_paths = ["23.jpg", "24.jpg", "25.jpg", "36.jpg", "50.jpg"]
images = []
for path in image_paths:
    img = load_img(path, target_size=(224, 224))  # Resizing the images to a common size
    img_array = img_to_array(img)
    images.append(img_array)
images = np.array(images)

# Model Architecture
model = models.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(224, 224, 3)),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(1, activation='sigmoid')
])

# Compile the Model
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# Training
labels = np.array([0, 1, 0, 1, 0])  # Example labels, replace with your actual labels
model.fit(images, labels, epochs=10, batch_size=32)

# Evaluation (Optional)
# test_images = [...]  # Load and preprocess your test images
# test_labels = [...]  # Actual labels for test images
# test_loss, test_acc = model.evaluate(test_images, test_labels)
# print('Test accuracy:', test_acc)

# Prediction
# new_images = [...]  # Load and preprocess new images you want to predict
# predictions = model.predict(new_images)
# print(predictions)


C:\Users\Ganesh Harsha\AppData\Roaming\Python\Python311\site-packages\keras\src\layers\convolutional\base_conv.py:99: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(


Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step - accuracy: 0.6000 - loss: 2.2959
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 379ms/step - accuracy: 0.6000 - loss: 2459.1792
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 239ms/step - accuracy: 0.6000 - loss: 722.5714
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 250ms/step - accuracy: 0.4000 - loss: 134.1272
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 249ms/step - accuracy: 1.0000 - loss: 0.0000e+00
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 239ms/step - accuracy: 0.8000 - loss: 19.1182
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 250ms/step - accuracy: 1.0000 - loss: 1.1916e-14
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 252ms/step - accuracy: 1.0000 - loss: 2.7206e-38
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 247ms/step - accuracy: 1.0000 - loss: 0.0000e+00
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 242ms/step - accuracy: 1.0000 - loss: 0.0000e+00


In [2]:
# Load and preprocess test images
test_images = []
for path in ["23.jpg", "24.jpg", "25.jpg", "36.jpg", "50.jpg"]:
    img = load_img(path, target_size=(224, 224))
    img_array = img_to_array(img)
    test_images.append(img_array)
test_images = np.array(test_images)

# Actual labels for test images
test_labels =np.array([0, 1, 0, 1, 0]) # You need to provide the actual labels for these test images

# Evaluation
test_loss, test_acc = model.evaluate(test_images, test_labels)
print('Test accuracy:', test_acc)

# Prediction
new_images = test_images  # You can use the same test images for prediction
predictions = model.predict(new_images)
print(predictions)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 331ms/step - accuracy: 1.0000 - loss: 0.0000e+00
Test accuracy: 1.0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step
[[0.]
 [1.]
 [0.]
 [1.]
 [0.]]


In [3]:
# Load and preprocess test images
test_images = []
for path in ["23.jpg", "24.jpg", "25.jpg", "36.jpg", "500.jpg"]:
    img = load_img(path, target_size=(224, 224))
    img_array = img_to_array(img)
    test_images.append(img_array)
test_images = np.array(test_images)

# Actual labels for test images
test_labels =np.array([0, 1, 0, 1, 0]) # You need to provide the actual labels for these test images

# Evaluation
test_loss, test_acc = model.evaluate(test_images, test_labels)
print('Test accuracy:', test_acc)

# Prediction
new_images = test_images  # You can use the same test images for prediction
predictions = model.predict(new_images)
print(predictions)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 1.0000 - loss: 0.0000e+00
Test accuracy: 1.0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step
[[0.]
 [1.]
 [0.]
 [1.]
 [0.]]


In [4]:
# Load and preprocess test images
test_images = []
for path in ["23.jpg", "24.jpg", "24.jpg", "25.jpg", "500.jpg"]:
    img = load_img(path, target_size=(224, 224))
    img_array = img_to_array(img)
    test_images.append(img_array)
test_images = np.array(test_images)

# Actual labels for test images
test_labels =np.array([0, 1, 0, 1, 0]) # You need to provide the actual labels for these test images

# Evaluation
test_loss, test_acc = model.evaluate(test_images, test_labels)
print('Test accuracy:', test_acc)

# Prediction
new_images = test_images  # You can use the same test images for prediction
predictions = model.predict(new_images)
print(predictions)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - accuracy: 0.6000 - loss: 68.6454
Test accuracy: 0.6000000238418579
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step
[[0.]
 [1.]
 [1.]
 [0.]
 [0.]]


In [8]:
# Load and preprocess test images
test_images = []
for path in ["23.jpg", "24.jpg", "25.jpg", "36.jpg", "50.jpg"]:
    img = load_img(path, target_size=(224, 224))
    img_array = img_to_array(img)
    test_images.append(img_array)
test_images = np.array(test_images)

# Actual labels for test images
test_labels =np.array([0, 1, 0, 1, 0]) # You need to provide the actual labels for these test images

# Evaluation
test_loss, test_acc = model.evaluate(test_images, test_labels)
print('Test accuracy:', test_acc)

# Prediction
new_images = test_images  # You can use the same test images for prediction
predictions = model.predict(new_images)
print(predictions)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 1.0000 - loss: 0.0000e+00
Test accuracy: 1.0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
[[0.]
 [1.]
 [0.]
 [1.]
 [0.]]
